checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    paths: ["calculator/*", "tests/*"]
build:
    tests:
        before:
            - pip install coverage
            - pip install tox
        after:
            - command: 'tox'