checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    paths: ["calculator/*", "tests/*"]
build:
    environment:
        python: ">=3.8"
    override:
        - true
    coverage:
        file: '.coverage'
    tests:
        before:
            - pip install coverage
            - pip install tox
        after:
            - command: 'tox'
            # config_file: '.coveragerc'
            # format: 'py-cc'
        # - py-scrutinizer-run