checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    paths: ["calculator/*", "tests/*"]
build:
    nodes:
        coverage:
            tests:
                override:
                    - command: './run-tests.sh'
                      coverage:
                        file: ".coverage"
    tests:
        before:
            - pip install coverage
            - pip install tox
        after:
            - command: 'tox'